apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: nginx-staging

namePrefix: staging-

commonLabels:
  environment: staging

replicas:
- name: nginx-deployment
  count: 2